### ISSUE TITLE
In windows7, how to solve?

### ISSUE THREAD

**Issue by xiaowuming** [artygus/ios-webkit-debug-proxy-win32#10]
$ ios-webkit-debug-proxy.exe
connect: No error
Could not set socket to non-blocking: No error
Unable to subscribe to device add/remove events

**Comment by artygus** [comment]
@xiaowuming can you confirm that iTunes (or Apple Mobile Device service) is running?

**Comment by artygus** [comment]
closing the issue since no reply form OP
