### ISSUE TITLE
Proxy crashes at connecting to the device (iOS 8.4)

### ISSUE THREAD

**Issue by DarkDaskin** [artygus/ios-webkit-debug-proxy-win32#12]
`NULL` SystemBUID is returned [here](https://github.com/artygus/libimobiledevice/blob/10c30ca26bf924c246043bdfc179aae2ca9be8e3/src/lockdown.c#L748) so the next line crashes with access violation.

The version bundled with [Valence](https://github.com/mozilla/valence/) crashes as well.

No crash occurs with the same device on latest Linux version (though it does not work anyway due to https://github.com/google/ios-webkit-debug-proxy/issues/82).

**Comment by artygus** [comment]
thanks for the report, I'll look into the issue

**Comment by artygus** [comment]
@DarkDaskin I guess it should be fixed with the latest libimobiledevice, check out this [build](http://sourceforge.net/projects/ios-webkit-debug-proxy-win32/files/test-builds/ios-webkit-debug-proxy-mingw32.zip/download)
