### ISSUE TITLE
It sees the device but it fails to see the content of the page in Safari

### ISSUE THREAD

**Issue by bogo26** [artygus/ios-webkit-debug-proxy-win32#13]
It posts this message in console:
![image](https://cloud.githubusercontent.com/assets/5627060/10509791/d7685344-7337-11e5-9409-e2c95f6abf8f.png)

On localhost:9221:
![image](https://cloud.githubusercontent.com/assets/5627060/10509814/fc816008-7337-11e5-9834-8582ff70f06a.png)

The Apple Mobile Device Service is working.
Tested on iPad 4 (iOS 9.0) and iPad (iOS 8.4.1)

Am I missing something?

**Comment by artygus** [comment]
@bogo26 libimobiledevice stack need update but I can't do it right now, I'll make a new build in a week or so

**Comment by bogo26** [comment]
ok, thanks for the fast response

have a nice day.
Bogdan :D

**Comment by artygus** [comment]
@bogo26 please try this [build](http://sourceforge.net/projects/ios-webkit-debug-proxy-win32/files/test-builds/ios-webkit-debug-proxy-mingw32.zip/download)

**Comment by liabru** [comment]
Same problem, I now get the following using the new build:

    Listing devices on :9221
    Unable to connect to iPhone (2) (...)
      Please verify that Settings > Safari > Advanced > Web Inspector = ON

I have enabled Web Inspector, but the message still shows. I'm on Windows 10 and iOS 9.2.

**Comment by artygus** [comment]
@bogo26 @liabru just fixed the issue with hanging sockets, please checkout updated [build](http://sourceforge.net/projects/ios-webkit-debug-proxy-win32/files/test-builds/ios-webkit-debug-proxy-mingw32.zip/download)

**Comment by fakhrulhilal** [comment]
I tried the latest build (above comment) and now it works as expected. Very thanks. It's really helpful.

**Comment by artygus** [comment]
@fakhrulhilal you're welcome
