### ISSUE TITLE
Invalid message error

### ISSUE THREAD

**Issue by jasono89** [artygus/ios-webkit-debug-proxy-win32#15]
Hi,

When I use the ios webkit debug proxy on Windows 7 I receive following error, when I plug in the iPad:
Invalid message _rpc_reportConnectedApplicationList: <dict>
        <key>WIRApplicationDictionaryKey</key>
        <dict>
                <key>PID:66</key>
                <dict>
                        <key>WIRApplicationIdentifierKey</key>
                        <key>PID:66</key>
                        <key>WIRIsApplicationProxyKey</key>
                        <false/>
                        <key>WIRApplicationNameKey</key>
                        <string></string>
                        <key>WIRApplicationBundleIdentifierKey</key>
                        <string>lockdownd</string>
                        <key>WIRIsApplicationActiveKey</key>
                        <integer>1</integer>
                </dict>
        </dict>
</dict>

Can anyone help? It worked fine a few weeks ago. 

Thanks & Regards,
Jason

**Comment by artygus** [comment]
Hi Jason, please try mingw32 build, you can find a link in the readme. But
it only works with external  frontend, see '-f' parameter

**Comment by jasono89** [comment]
Great. Works like a charm... 
Thank you!!
