### ISSUE TITLE
Unable to connect to chrome-devtools-frontend.appspot.com:80

### ISSUE THREAD

**Issue by anifox2** [artygus/ios-webkit-debug-proxy-win32#17]
Everytime I try to connect to Safari on my iPhone 6S, I can see my device in the list and my open tabs but when i press a tab, I get this error message:

Unable to connect to chrome-devtools-frontend.appspot.com:80

I am running Chrome 50 on Windows 8.1 and using ios-webkit-debug-proxy-mingw32

**Comment by artygus** [comment]
@anifox2 mingw build is not production ready yet, please try "-f http://chrome-devtools-frontend.appspot.com/static/27.0.1453.93/devtools.html". Chrome dev protocol went too far from what Safari has and latest dev tools wouldn't show you styles at all (at least it didn't work 3-4 months ago), I suggest using dev tools extracted from webkit https://github.com/artygus/webkit-webinspector

**Comment by anifox2** [comment]
I have already tried https://github.com/artygus/webkit-webinspector and I'm just getting a white page. Using "-f http://chrome-devtools-frontend.appspot.com/static/27.0.1453.93/devtools.html" gives me the same error message: Unable to connect to chrome-devtools-frontend.appspot.com:80

**Comment by anifox2** [comment]
https://github.com/artygus/webkit-webinspector just crashes on start now when trying again. Here is the error message: events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1366:5)
    at Function.listen (C:\Users\MyAccount\Downloads\webkit-webinspector-master\
node_modules\connect\index.js:217:24)
    at Object.<anonymous> (C:\Users\MyAccount\Downloads\webkit-webinspector-mast
er\server.js:26:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)

**Comment by artygus** [comment]
@anifox2 hm, then you cat try to run `ios_webkit_debug_proxy -F` and then navigate to `https://chrome-devtools-frontend.appspot.com/static/27.0.1453.93/devtools.html?ws=localhost:9222/devtools/page/1` in your browser

**Comment by anifox2** [comment]
1. If I use the normal "ios-webkit-debug-proxy-win32" i get this error when starting it with "ios-webkit-debug-proxy.exe -F": 
Invalid message _rpc_reportConnectedApplicationList: <dict>
        <key>WIRApplicationDictionaryKey</key>
        <dict>
                <key>PID:409</key>
                <dict>
                        <key>WIRApplicationIdentifierKey</key>
                        <key>PID:409</key>
                        <key>WIRIsApplicationProxyKey</key>
                        <false/>
                        <key>WIRApplicationNameKey</key>
                        <string>Safari</string>
                        <key>WIRApplicationBundleIdentifierKey</key>
                        <string>com.apple.mobilesafari</string>
                        <key>WIRIsApplicationActiveKey</key>
                        <integer>1</integer>
                </dict>
                <key>PID:411</key>
                <dict>
                        <key>WIRApplicationIdentifierKey</key>
                        <key>PID:411</key>
                        <key>WIRIsApplicationProxyKey</key>
                        <true/>
                        <key>WIRApplicationNameKey</key>
                        <string></string>
                        <key>WIRApplicationBundleIdentifierKey</key>
                        <string>com.apple.WebKit.WebContent</string>
                        <key>WIRIsApplicationActiveKey</key>
                        <integer>1</integer>
                        <key>WIRHostApplicationIdentifierKey</key>
                        <key>PID:409</key>
                </dict>
                <key>PID:71</key>
                <dict>
                        <key>WIRApplicationIdentifierKey</key>
                        <key>PID:71</key>
                        <key>WIRIsApplicationProxyKey</key>
                        <false/>
                        <key>WIRApplicationNameKey</key>
                        <string></string>
                        <key>WIRApplicationBundleIdentifierKey</key>
                        <string>lockdownd</string>
                        <key>WIRIsApplicationActiveKey</key>
                        <integer>1</integer>
                </dict>
        </dict>
</dict>

And when trying to connect to https://chrome-devtools-frontend.appspot.com/static/27.0.1453.93/devtools.html?ws=localhost:9222/devtools/page/1 I get these two error messages (if I open developer tools on the site): 

DevTools.js:3104 Mixed Content: The page at 'https://chrome-devtools-frontend.appspot.com/static/27.0.1453.93/devtools.html?ws=localhost:9222/devtools/page/1' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://localhost:9222/devtools/page/1'. This request has been blocked; this endpoint must be available over WSS.WebInspector.loaded @ DevTools.js:3104windowLoaded @ DevTools.js:3302
DevTools.js:3104 
Uncaught SecurityError: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.

2. If I open "ios-webkit-debug-proxy-mingw32" using ios_webkit_debug_proxy.exe -F, I do not get any errors until I open https://chrome-devtools-frontend.appspot.com/static/27.0.1453.93/devtools.html?ws=localhost:9222/devtools/page/1. Then I get the same security error described above in the js console (if I open developer tools)

**Comment by anifox2** [comment]
In both cases, https://chrome-devtools-frontend.appspot.com/static/27.0.1453.93/devtools.html?ws=localhost:9222/devtools/page/1 is just a blank page with a grey bar at the top with 3 unclickable buttons and a light grey bar at the bottom except the errors in the console. 
![Chrome](https://cloud.githubusercontent.com/assets/2982688/14582838/2e4516b6-0410-11e6-8dcc-df75ee5b24c1.png)
![Developer console](https://cloud.githubusercontent.com/assets/2982688/14582840/437314ca-0410-11e6-97f9-0fb6077d3a68.png)

**Comment by artygus** [comment]
@anifox2 just click on the shield icon https://github.com/artygus/ios-webkit-debug-proxy-win32#troubleshooting

**Comment by anifox2** [comment]
That worked! Thank you!

**Comment by galziv** [comment]
Hi, the solution worked for me, but the devtool is very old and doesn't have websocket tab in the network panel which I really need. 
Which other version than '27.0.1453.93' is valid?

**Comment by artygus** [comment]
hi @galziv check out alternatives to chrome devtools here https://github.com/google/ios-webkit-debug-proxy#devtools-note, if you're stuck with chrome dev tools, you could try http://frontend.chrome-dev.tools/serve_rev/@198714/inspector.html

**Comment by galziv** [comment]
thanks for the prompt answer! i'll take a look
