### ISSUE TITLE
docs: how to install instructions

### ISSUE THREAD

**Issue by staabm** [artygus/ios-webkit-debug-proxy-win32#18]
do you provide some information on how to setup the debug proxy on windows?

I just downloaded the msvc release build from SourceForge (linked from the readme), extracted it and started the ios-webkit-debug-proxy.exe.

It errors in a cmd windows:
![proxy](https://cloud.githubusercontent.com/assets/120441/15218885/15e34456-1862-11e6-828e-974e49d1b5ca.png)

My workstation is already configured to debug a Android phone with Chrome via ADB.

thx!

env:
- win7x64
- iphone6 on ios9
- chrome 51.0.2704.36 beta-m

**Comment by artygus** [comment]
@staabm there's no specific about that, except you need Apple Mobile Device service running, current version is a bit outdated, please try [mingw32 build](http://sourceforge.net/projects/ios-webkit-debug-proxy-win32/files/test-builds/ios-webkit-debug-proxy-mingw32.zip/download)

**Comment by littleguga** [comment]
@staabm I also have win7x64, it's okay with me.

* Connect iPhone to laptop with cable
* Set ```Settings > Safari > Advanced > Web Inspector = ON```
* start ```ios-webkit-debug-proxy -f chrome-devtools://devtools/bundled/inspector.html``` 
* navigate to http://localhost:9221/
