### ISSUE TITLE
Invalid message _rpc_reportConnectedApplicationList: 

### ISSUE THREAD

**Issue by fredbutters** [artygus/ios-webkit-debug-proxy-win32#21]
Windows 10
Firefox Developer Edition
iPad
Trying to follow along with this tutorial: http://johnnyzone.com/2016/02/debug-a-website-in-ios-safari-on-windows/

I saw other issues like this reported, so I downloaded and ran this one:
http://sourceforge.net/projects/ios-webkit-debug-proxy-win32/files/test-builds/ios-webkit-debug-proxy-mingw32.zip/download

That appears to run, I see a command window with this:
Listing devices on :9221
Connected :9222 to <username>ΓÇÖs iPad (cae8a75c1e724740597b934850e4f7df4ff6e5e6)

Then the WebIDE shows the device is connected, then disconnects and the Command window then shows:

Listing devices on :9221
Connected :9222 to <username>ΓÇÖs iPad (cae8a75c1e724740597b934850e4f7df4ff6e5e6)
Unknown app_id PID:171
Invalid message _rpc_applicationSentListing: <dict>
        <key>WIRApplicationIdentifierKey</key>
        <string>PID:171</string>
        <key>WIRListingKey</key>
        <dict>
        </dict>
</dict>
Disconnected :9222 from mark.barryΓÇÖs iPad (cae8a75c1e724740597b934850e4f7df4ff6e5e6)

The browser console shows a ton of errors too
A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

valence:PowerShell -Command ps ios-webkit-debug-proxy: I ios-proxy.js:200
Connection status changed: connecting app-manager.js:160
Connection status changed: connected app-manager.js:160
 protocol.js:907
Connection status changed: disconnecting app-manager.js:160
Connection status changed: disconnected app-manager.js:160
unknownError Promise-backend.js:936

Date: Wed May 25 2016 09:10:42 GMT-0700 (Pacific Standard Time)
Full Message: unknownError
Full Stack: JS frame :: resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js :: PendingErrors.register :: line 191
JS frame :: resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js :: this.PromiseWalker.completePromise :: line 714
JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/client/webide/modules/tab-store.js :: TabStore.prototype.listTabs/< :: line 104
JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/client/main.js :: DebuggerClient.requester/</< :: line 294
JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js :: exports.makeInfallible/< :: line 101
JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js :: emitOnObject :: line 112
JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js :: emit :: line 89
JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/client/main.js :: Request.prototype.emit :: line 1218
JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/client/main.js :: DebuggerClient.prototype.onPacket/emitReply :: line 1004
JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/client/main.js :: DebuggerClient.prototype.onPacket :: line 1006
JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/transport/transport.js :: LocalDebuggerTransport.prototype.send/< :: line 569
JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js :: exports.makeInfallible/< :: line 101
JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js :: exports.makeInfallible/< :: line 101

**Comment by patrickracicot** [comment]
+1

**Comment by MigFerreira** [comment]
+1

**Comment by artygus** [comment]
please checkout [new build](https://sourceforge.net/projects/ios-webkit-debug-proxy-win32/files/test-builds/ios-webkit-debug-proxy-win64.zip/download)

**Comment by artygus** [comment]
should be fixed, the latest build available via scoop now, for reference check out https://github.com/google/ios-webkit-debug-proxy/blob/master/README.md
