### ISSUE TITLE
Not working on iOS10

### ISSUE THREAD

**Issue by roryaherne** [artygus/ios-webkit-debug-proxy-win32#22]
Just a heads up. I tried with mingw32 and win32.

 **mingw32**

`Listing devices on :9221
Could not connect to lockdownd. Exiting.: No error
Unable to attach 5629881f4f4f7807e05d084f6c2e8916bb32549e inspector`

**win32 (1st level in folder)**

> Invalid message _rpc_reportConnectedApplicationList: <dict>
>         <key>WIRApplicationDictionaryKey</key>
>         <dict>
>                 <key>PID:65</key>
>                 <dict>
>                         <key>WIRRemoteAutomationEnabledKey</key>
>                         <false/>
>                         <key>WIRIsApplicationActiveKey</key>
>                         <integer>1</integer>
>                         <key>WIRIsApplicationReadyKey</key>
>                         <false/>
>                         <key>WIRApplicationIdentifierKey</key>
>                         <key>PID:65</key>
>                         <key>WIRIsApplicationProxyKey</key>
>                         <false/>
>                         <key>WIRApplicationNameKey</key>
>                         <string></string>
>                         <key>WIRApplicationBundleIdentifierKey</key>
>                         <string>com.apple.webinspectord</string>
>                 </dict>
>                 <key>PID:1330</key>
>                 <dict>
>                         <key>WIRRemoteAutomationEnabledKey</key>
>                         <false/>
>                         <key>WIRIsApplicationActiveKey</key>
>                         <integer>1</integer>
>                         <key>WIRIsApplicationReadyKey</key>
>                         <false/>
>                         <key>WIRApplicationIdentifierKey</key>
>                         <string>PID:1330</string>
>                         <key>WIRIsApplicationProxyKey</key>
>                         <false/>
>                         <key>WIRApplicationNameKey</key>
>                         <string>Safari</string>
>                         <key>WIRApplicationBundleIdentifierKey</key>
>                         <string>com.apple.mobilesafari</string>
>                 </dict>
>                 <key>PID:1332</key>
>                 <dict>
>                         <key>WIRRemoteAutomationEnabledKey</key>
>                         <false/>
>                         <key>WIRIsApplicationActiveKey</key>
>                         <integer>1</integer>
>                         <key>WIRIsApplicationReadyKey</key>
>                         <false/>
>                         <key>WIRApplicationIdentifierKey</key>
>                         <string>PID:1332</string>
>                         <key>WIRIsApplicationProxyKey</key>
>                         <true/>
>                         <key>WIRApplicationNameKey</key>
>                         <string></string>
>                         <key>WIRApplicationBundleIdentifierKey</key>
>                         <string>com.apple.WebKit.WebContent</string>
>                         <key>WIRHostApplicationIdentifierKey</key>
>                         <string>PID:1330</string>
>                 </dict>
>         </dict>
> </dict>

**win32 (second level in folder)**

`Could not connect to lockdownd. Exiting.: No error
Unable to attach 5629881f4f4f7807e05d084f6c2e8916bb32549e inspector`

Please let me know if I can provide any more info to help.

**Comment by artygus** [comment]
hi @roryaherne thanks for the report, iOS 10 is not supported yet by the original utility the issue is already here https://github.com/google/ios-webkit-debug-proxy/issues/144

**Comment by artygus** [comment]
@roryaherne please check out this build https://sourceforge.net/projects/ios-webkit-debug-proxy-win32/files/test-builds/ios-webkit-debug-proxy-mingw32-ios10.zip/download

**Comment by ethan-deng** [comment]
This build works for me for iOS 10.

https://sourceforge.net/projects/ios-webkit-debug-proxy-win32/files/test-builds/ios-webkit-debug-proxy-win64.zip/download
