### ISSUE TITLE
iOS10 support

### ISSUE THREAD

**Issue by jshanman** [artygus/ios-webkit-debug-proxy-win32#24]
When I try to connect to an iOS10 device, I get the following error:

`
Listing devices on :9221
Could not connect to lockdownd. Existing.: No error
Unable to attach {$hash} inspector
`
My environment:
Windows 10
Google Chrome 52.0.2743.116
iTunes 12.5.1.21 (installed today & rebooted machine)

iPhone SE mllx2ll/a
iOS 10.0.1 14a403
Safari 602.1.5

I downloaded this binary and have run it as a regular user and administrator.
http://heanet.dl.sourceforge.net/project/ios-webkit-debug-proxy-win32/test-builds/ios-webkit-debug-proxy-mingw32-ios10.zip

**Comment by artygus** [comment]
Hi @jshanman there's a similar issue #22, to sum up please check the out another [build](https://sourceforge.net/projects/ios-webkit-debug-proxy-win32/files/test-builds/ios-webkit-debug-proxy-mingw32-ios10.zip/download)

**Comment by jshanman** [comment]
Hi @artygus thank you for the reply.  That is the build I tested with and linked above.  The error I'm reporting is against that build.  I opened a new issue since that one was closed.

**Comment by artygus** [comment]
@jshanman oh sorry didn't read issue to the end, I'll take a look 👍

**Comment by ShinyLeee** [comment]
Faced the same issues.

**Comment by artygus** [comment]
@jshanman looks like libimobiledevice needs to be updated to master version to overcome the issue, I'll make another build this week

**Comment by Murmand** [comment]
Same issue here, how does it look with new build?

**Comment by ChristianBcn** [comment]
Same for me... I'm looking forward this!!

Thanks

**Comment by artygus** [comment]
my build env messed up, I'll take another try this week

**Comment by ChristianBcn** [comment]
I appreciate your help :)

**Comment by davidpede** [comment]
Same issue. Any news on when iOS 10 support is coming?

**Comment by artygus** [comment]
@davidpede don't have a spare hour to make another build, I'll post here when it's done

**Comment by strideynet** [comment]
Any news??

**Comment by mikejohnpettitt** [comment]
Interested to know if there any updates.

**Comment by artygus** [comment]
few more days guys, almost there

**Comment by Ayverie** [comment]
Also facing this issue. Was starting to wonder if I'm just cursed... Thank you for working on update!

**Comment by artygus** [comment]
hey guys, please check out [new build](https://sourceforge.net/projects/ios-webkit-debug-proxy-win32/files/test-builds/ios-webkit-debug-proxy-win64.zip/download)

**Comment by ChristianBcn** [comment]
Thank you very much, artygus!! We appreciate your work on, it works really good!!

**Comment by fred-perkins** [comment]
Awesome stuff. Got it working with chrome dev tools. Only thing i noticed was the "Console" & "Network" tabs aren't functional

**Comment by artygus** [comment]
@fred-perkins yeah, safari and chrome tools are getting farther in terms of protocols they're using and frontend tools implementations, but it's beyond the scope of the utility. You could try using safari webinspector on windows machine, e.g. using an [extracted dev tools](https://github.com/artygus/webkit-webinspector) from webkit repo

**Comment by fred-perkins** [comment]
@artygus Makes alot of sense. Got it working using the webkit inspector.  Thanks for the help!
