### ISSUE TITLE
Cannot connect - please help

### ISSUE THREAD

**Issue by RealMakAttak** [artygus/ios-webkit-debug-proxy-win32#25]
Hello all, 

I am desperately trying to remotely debug safari and other browsers from my iphone.

I followed these instructions: http://johnnyzone.com/2016/02/debug-a-website-in-ios-safari-on-windows/

 I downloaded and installed itunes, my device is recognised. I turned developer tools on my phone on, opened up a tab, started webide in firefox and click the option "Safari, Firefox, and other WebViews on iOS" but no devices are recognised.

I then downloaded the "ios-webkit-debug-proxy-mingw32" as recommended in the article and ran the "ios-webkit-debug-proxy.exe" however, I keep getting this error message...

"Listing devices on :9221
Could not connect to lockdownd. Exiting.: No error
Unable to attach f254e44f7bc6c8b89610f08b019b9a9ec8204b1f inspector"

Can anyone kindly help me?

**Comment by artygus** [comment]
hi @RealMakAttak does device run on ios 10?

**Comment by RealMakAttak** [comment]
Arty, 

Thank you for your prompt reply.

It's an iphone 5 running iOS 10.1.1

I'm on a windows machine with 10 running. 

Thanks

**Comment by artygus** [comment]
@RealMakAttak I'm working on the iOS10 support #24 issue please look for updates in this thread

**Comment by RealMakAttak** [comment]
Thanks Arty, will do
