### ISSUE TITLE
align code to 1.7.1

### ISSUE THREAD

**Issue by webmanAv** [artygus/ios-webkit-debug-proxy-win32#27]
Hi,
Do you plan to align windows code to match 
https://github.com/google/ios-webkit-debug-proxy/releases/tag/1.7.1
Thanks,
Aviram

**Comment by artygus** [comment]
Hi @webmanAv I'm working on mingw branch of ios-webkit-debug-proxy, so windows binaries would always be up to date. I'm not planning to support VS project

PS. I hope to get it done by the end of the month

**Comment by webmanAv** [comment]
Thanks, it is absolutely great step.
I'm looking forward for it.
Thanks,
 Aviram
