### ISSUE TITLE
ios-webkit-debug-proxy/ as submodule?

### ISSUE THREAD

**Issue by auchenberg** [artygus/ios-webkit-debug-proxy-win32#28]
Looking at https://github.com/artygus/ios-webkit-debug-proxy-win32/tree/master/ios-webkit-debug-proxy, it doesnt look like this win32 fork has made any changes to https://github.com/google/ios-webkit-debug-proxy.

Could the codebase be referenced as a submodule for easier upgrades?

**Comment by artygus** [comment]
@auchenberg I'm finally working on mingw branch https://github.com/google/ios-webkit-debug-proxy/tree/mingw64. This project was not well-written, I hope I'll do better this time

**Comment by auchenberg** [comment]
Cool! Let me know if I can help in any way @artygus

**Comment by artygus** [comment]
google/ios-webkit-debug-proxy#193 is finally merged in
