### ISSUE TITLE
Doesn't recognize iPhone with iOS 10.0

### ISSUE THREAD

**Issue by laurennlam** [artygus/ios-webkit-debug-proxy-win32#30]
I tried to debug a web page from an apple device (iPhone with iOS 10.3) on windows by using WEBIde from Firefox. It works well with an iPhone with an iOS of 9.1 but doesn't work with an iPhone with iOS 10.3.
Ad RemoteDebug/remotedebug-ios-webkit-adapter describe, it seems that :

> iOS 10 on Windows: Please be aware that iOS10 debugging might not work on Windows as the bundled version of /ios-webkit- debug-proxy-win32 is out of date.

Will you have a project to update your executable ? Or do you have an other solution ?

**Comment by artygus** [comment]
the information in README is incorrect, latest win binaries are up to date and available via scoop on windows, or directly by [link](https://downloads.sourceforge.net/project/ios-webkit-debug-proxy-win32/v1.7.1/ios-webkit-debug-proxy-1.7.1-x64-bin.zip)

**Comment by laurennlam** [comment]
Thanks @artygus !
