### ISSUE TITLE
Could not connect to iOS 11 device

### ISSUE THREAD

**Issue by yostyle** [artygus/ios-webkit-debug-proxy-win32#31]
Hello,
I use version 1.7.1. It works well with iOS 10.
When I plug an iOS 11 device, I have this error in console : 
```
Could not connect to lockdownd. Exiting.: No error
Unable to attach your_device_uuid inspector
```

**Comment by artygus** [comment]
you need a fresh version of the utility, it is available [here](https://github.com/google/ios-webkit-debug-proxy/releases)
