### ISSUE TITLE
Can't connect to IOS 11?

### ISSUE THREAD

**Issue by mhofer1976** [artygus/ios-webkit-debug-proxy-win32#32]
I had this working already before i upgraded my IPad to IOS 11.

Now i'm getting:
Listing devices on :9221
Could not connect to lockdownd. Exiting.: No error
Unable to attach 58d2763ce8d6cd7f1565c44a31f5b5c613c3fdd0 inspector

Would appreciate the help to get this going again.

**Comment by artygus** [comment]
hi @mhofer1976, do you use latest version from scoop? if not, please use https://github.com/google/ios-webkit-debug-proxy/releases to obtain windows binaries. 

TODO: update readme to point to original iwdp page to avoid confusion in the future

**Comment by mhofer1976** [comment]
Wow - that's what i call speed!

YES, it works like a charm. THANKS  A LOT artygus!
