### ISSUE TITLE
Supporting Windows XP

### ISSUE THREAD

**Issue by past** [artygus/ios-webkit-debug-proxy-win32#5]
I'm trying to build the proxy for Windows XP and I get:

Error	102	error C3861: 'htonll': identifier not found	C:\Users\past\Documents\GitHub\ios-webkit-debug-proxy-win32\ios-webkit-debug-proxy\src\websocket.c	351	1	ios-webkit-debug-proxy

Before I look into this, has anyone tried this before?

**Comment by artygus** [comment]
@past never tried before, this block of code required for the patch https://github.com/google/ios-webkit-debug-proxy/pull/60 . I'll try to add windows xp support this weekend

**Comment by artygus** [comment]
@past please try to build with the latests changes

**Comment by past** [comment]
Thanks for the changes! I tried it, but it didn't work and I got the following errors on XP:

Could not set socket to non-blocking
Unable to subscribe to device add/remove events

This was on an almost vanilla XP installation with an administrator account. Any ideas?

**Comment by artygus** [comment]
@past eh.. no ideas. i'll setup winXP virtual machine and look more deeply

**Comment by past** [comment]
I don't have access to Windows XP myself, so I'm asking other folks to test it for me. The first one failed as I mentioned above, but the second one succeeded:

https://github.com/campd/valence/pull/147#issuecomment-75139276

The problem I reported above seems to be configuration-specific.

**Comment by artygus** [comment]
@past nice to hear, going to close the issue then. if you will experience any problems with this in the future please let me know
