### ISSUE TITLE
Won't run on Windows 8.1

### ISSUE THREAD

**Issue by Luke-SF** [artygus/ios-webkit-debug-proxy-win32#7]
I extracted the latest release and moved into C:\Program files, but it always says "The program can't start because MSVCR120.dll is missing from your computer".

I have Visual C++ 2005, 2008, 2010, 2012, 2013 installed and still it doesn't run.

**Comment by artygus** [comment]
@Luke-SF probably you need to install x86 version of microsoft visual c++ 2013 redistributable

**Comment by artygus** [comment]
@Luke-SF did it help?

**Comment by programmin1** [comment]
Yes but iTunes won't install, I don't see this error though. Thanks.
