### ISSUE TITLE
Connects to devices and lists them, but they do not get attached

### ISSUE THREAD

**Issue by zymotik** [artygus/ios-webkit-debug-proxy-win32#8]
Windows 7 64bit
Devices listed:
![devicelist](https://cloud.githubusercontent.com/assets/697029/6561381/d7fd8f6a-c688-11e4-8977-c92bd5817ea2.png)

But not available:
![noconnection](https://cloud.githubusercontent.com/assets/697029/6561401/fc97318c-c688-11e4-9595-4d3b18f8e382.png)

Netstat:
![netstat](https://cloud.githubusercontent.com/assets/697029/6561486/7f460144-c689-11e4-9daf-df95714440e6.png)

**Comment by artygus** [comment]
@zymotik with the latest iOS, 8.13?
I think i know the reason, will make a test build this evening

**Comment by zymotik** [comment]
@artygus I've tried this on iOS 8.1.3 iPad 2, iOS 7.0.4 iPhone & iPad Air. Thanks for the quick response!

**Comment by artygus** [comment]
@zymotik sorry for the delay, here's the build http://sourceforge.net/projects/ios-webkit-debug-proxy-win32/files/test-builds/ios-webkit-debug-proxy-win32-debug_rpcAppUpdated.zip/download

**Comment by zymotik** [comment]
I've given it a try, but it still doesn't work, sorry! Thanks for your effort on the build! 

Here's the log I get when attaching the iPad (iOS 7.0.4):
![output](https://cloud.githubusercontent.com/assets/697029/6614632/347a92e4-c894-11e4-9557-acb14f448463.png)

**Comment by zymotik** [comment]
I've given it a try, but it still doesn't work, sorry! Thanks for your effort on the build! 

Here's the log I get when attaching the iPad (iOS 7.0.4):
![output](https://cloud.githubusercontent.com/assets/697029/6614691/a7059642-c894-11e4-8430-697b91c5276f.png)

**Comment by zymotik** [comment]
@artygus I've given it a try, but it still doesn't work, sorry! Thanks for your effort on the build! 

Here's the log I get when attaching the iPad (iOS 7.0.4):
![output](https://cloud.githubusercontent.com/assets/697029/6614702/c1904b92-c894-11e4-8768-8226937485c1.png)

**Comment by zymotik** [comment]
I'm an idiot..... while debugging on a Mac, I realised I hadn't got the Web Inspector Enabled:
IOS >>> Settings >>> Safari >>> Advanced >>> Web Inspector

Sorry @artygus !

Now my issue is the insecure connection to localhost from a site that is https. I can fix that on the command line arg hopefully.

**Comment by artygus** [comment]
@zymotik oh, that easy! it's okay, no worries :)

**Comment by NelsonLamprecht** [comment]
I have the same issue, I have not installed Safari (not sure if that is a requirement). The localhost 9221 shows the device but the console has this error message and the port for the device is refused:
Invalid message _rpc_reportConnectedApplicationList: <dict>
        <key>WIRApplicationDictionaryKey</key>
        <dict>
                <key>PID:569</key>
                <dict>
                        <key>WIRApplicationIdentifierKey</key>
                        <key>PID:569</key>
                        <key>WIRIsApplicationProxyKey</key>
                        <false/>
                        <key>WIRApplicationNameKey</key>
                        <string></string>
                        <key>WIRApplicationBundleIdentifierKey</key>
                        <string>lockdownd</string>
                        <key>WIRIsApplicationActiveKey</key>
                        <integer>1</integer>
                </dict>
        </dict>
</dict>

**Comment by artygus** [comment]
@NelsonLamprecht thanks for the report, i will look into the issue

**Comment by artygus** [comment]
@NelsonLamprecht libplist needs update, gonna rebuild stuff in a few days

**Comment by artygus** [comment]
closing in regard to #13

**Comment by artygus** [comment]
@NelsonLamprecht check out this [build](http://sourceforge.net/projects/ios-webkit-debug-proxy-win32/files/test-builds/ios-webkit-debug-proxy-mingw32.zip/download)

**Comment by NelsonLamprecht** [comment]
I tried this build you posted: http://sourceforge.net/projects/ios-webkit-debug-proxy-win32/files/test-builds/ios-webkit-debug-proxy-mingw32.zip/download where I am able to see the 9221 listing of my iphone. Clicking on 9222 does nothing though and chrome reports the connection refused. I used the -d flag when starting the proxy and when I click on the 9222 port, the console prints this but the connect is not made...: 
ss.recv fd=636 len=0
ss.remove_fd(636)

**Comment by artygus** [comment]
@NelsonLamprecht too bad, I tested this build with WinXP only on my virtualbox vm. I'll let you know when I fix the problem, btw what win ver do you use?

**Comment by DitlevHB** [comment]
I am experiencing the same issue with iPhone iOS 9.2
I'm not able to access the device at all with the stable build.

I can see the device on localhost:9221 using the test-build you posted 6th of November and the connection keeps hanging, when clicking on the listed device. 

I'm using windows 10.

**Comment by artygus** [comment]
@DitlevHB @NelsonLamprecht just fixed the issue with hanging sockets, please checkout updated [build](http://sourceforge.net/projects/ios-webkit-debug-proxy-win32/files/test-builds/ios-webkit-debug-proxy-mingw32.zip/download)

**Comment by DitlevHB** [comment]
Great thanks,

I can now click on the device and see the list of available pages.
Although when i click on on of the available pages, i get a blank page with the following:

Unable to connect to chrome-devtools-frontend.appspot.com:80

Is the service down, or is this another issue further in the flow?

**Comment by artygus** [comment]
@DitlevHB oh yeap, that's some windows specific stuff, I'll look into the issue. I rarely use built-in frontend mechanism because it's slow as heck, for now you can use https://chrome-devtools-frontend.appspot.com/static/27.0.1453.93/devtools.html?ws=localhost:9222/devtools/page/1

**Comment by DitlevHB** [comment]
@artygus That works! 

Thanks a lot for the adjustments, it works with the url you provided.
