### ISSUE TITLE
Proxy/mobile Safari crashes on Pause Script execution

### ISSUE THREAD

**Issue by Graham-Phillips** [artygus/ios-webkit-debug-proxy-win32#9]
iPhone 5, iOS 7.0.1
Windows 7 64bit
Using devtools here:
http://chrome-devtools-frontend.appspot.com/static/27.0.1453.93/devtools.html

Clicking the Pause script execution button on the sources page crashes Safari on the device and sometimes the proxy server as well.

**Comment by artygus** [comment]
@Graham-Phillips I tried to pause script with latest iOS and a few other devtools vers and I can confirm the crash. Gonna investigate this stuff, thanks for the report!

**Comment by artygus** [comment]
@Graham-Phillips I'm still not sure if there anything I can do about the issue. You can try to debug with one of the webkit inspectors, I extracted a few versions [here](https://github.com/artygus/webkit-webinspector)
